<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'BoldMinded\\DataGrab\\Dependency\\DateError' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateError.php',
    'BoldMinded\\DataGrab\\Dependency\\DateException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateException.php',
    'BoldMinded\\DataGrab\\Dependency\\DateInvalidOperationException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateInvalidOperationException.php',
    'BoldMinded\\DataGrab\\Dependency\\DateInvalidTimeZoneException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateInvalidTimeZoneException.php',
    'BoldMinded\\DataGrab\\Dependency\\DateMalformedIntervalStringException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateMalformedIntervalStringException.php',
    'BoldMinded\\DataGrab\\Dependency\\DateMalformedPeriodStringException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateMalformedPeriodStringException.php',
    'BoldMinded\\DataGrab\\Dependency\\DateMalformedStringException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateMalformedStringException.php',
    'BoldMinded\\DataGrab\\Dependency\\DateObjectError' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateObjectError.php',
    'BoldMinded\\DataGrab\\Dependency\\DateRangeError' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateRangeError.php',
    'BoldMinded\\DataGrab\\Dependency\\Deprecated' => $vendorDir . '/symfony/polyfill-php84/Resources/stubs/Deprecated.php',
    'BoldMinded\\DataGrab\\Dependency\\NoDiscard' => $vendorDir . '/symfony/polyfill-php85/Resources/stubs/NoDiscard.php',
    'BoldMinded\\DataGrab\\Dependency\\Normalizer' => $vendorDir . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
    'BoldMinded\\DataGrab\\Dependency\\Override' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/Override.php',
    'BoldMinded\\DataGrab\\Dependency\\ReflectionConstant' => $vendorDir . '/symfony/polyfill-php84/Resources/stubs/ReflectionConstant.php',
    'BoldMinded\\DataGrab\\Dependency\\SQLite3Exception' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/SQLite3Exception.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
